### ISSUE TITLE
XPath does not work on large XML files

### ISSUE THREAD

**Issue by George-Weilenmann-RJ** [eGust/xml-plus.chrome-extension#35]
The file being worked with is a large 200MB Validated XML file lacking an XSLT. XML-Plus was able to load the file and render the XML Tree which is quite nice. However, XPath queries that were validated with another tool, fail to return results.

**Comment by eGust** [comment]
Hi @George-Weilenmann-RJ 
Unfortunately, the XPath functionality is provided by the browser:
https://developer.mozilla.org/en-US/docs/Web/API/Document/evaluate

The version shipped with the browser is probably too old and I can't help with that.
